#4 implement sidebar in homescreen
DECK1xUCN/DispatchApp pull request #9
Opened 2023-03-18 12:58 UTC by Boti28

helicopter go brrrrrrrrr with icons

2023-03-18 14:33 UTC, Piratepie requested changes
Change the naming of certain files in `assets` and the `SideBar.dart` file to follow cameCase convention: `lowerUperNoDash`

2023-03-18 14:33 UTC, Piratepie commented on client/lib/pages/SideBar.dart
change name of file to follow dart convention  
change to `sidebar.dart`

2023-03-18 14:33 UTC, Piratepie commented on client/assets/deck1-logo.svg
Make assets names consistent  
`lowerUperNoDash`

2023-03-18 14:38 UTC, ttommmy approved these changes
Nothing else to add besides what @Piratepie  said.

2023-03-18 14:43 UTC, Piratepie approved these changes
nicuh

2023-03-18 14:43 UTC, merged

2023-03-20 08:25 UTC, tomassabol commented
is text background implemented for the current page in navbar?